import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import '../models/project_application.dart';
import '../models/project_offer.dart';

/// Service for managing project applications
class ApplicationService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  /// Collection reference for applications
  CollectionReference get _applicationsCollection =>
      _firestore.collection('project_applications');

  /// Apply to a project offer
  /// Saves the application to Firestore and links it to user and project
  Future<void> applyToProject(ProjectOffer project) async {
    final user = _auth.currentUser;
    if (user == null) {
      throw Exception('User must be logged in to apply');
    }

    try {
      // Check if user already applied to this project
      final existingApplication = await _applicationsCollection
          .where('userId', isEqualTo: user.uid)
          .where('projectId', isEqualTo: project.id)
          .limit(1)
          .get();

      if (existingApplication.docs.isNotEmpty) {
        debugPrint('ℹ️ [APPLICATION] User already applied to this project');
        throw Exception('You have already applied to this project');
      }

      // Get NGO ID from project (if available)
      String? ngoId = project.ngoId;
      
      // If ngoId is not set in project, try to find it by instagramAccount (backward compatibility)
      if (ngoId == null) {
        try {
          final ngoQuery = await _firestore
              .collection('ngos')
              .where('instagramUsername', isEqualTo: project.instagramAccount)
              .limit(1)
              .get();
          
          if (ngoQuery.docs.isNotEmpty) {
            ngoId = ngoQuery.docs.first.id;
            debugPrint('✅ [APPLICATION] Found NGO by instagramAccount: $ngoId');
          }
        } catch (e) {
          debugPrint('⚠️ [APPLICATION] Could not find NGO for project: $e');
        }
      }

      // Create application document
      final application = ProjectApplication(
        id: '', // Will be generated by Firestore
        userId: user.uid,
        userEmail: user.email ?? '',
        projectId: project.id,
        projectTitle: project.title,
        ngoId: ngoId,
        appliedAt: DateTime.now(),
        status: ApplicationStatus.pending,
      );

      // Save to Firestore
      await _applicationsCollection.add(application.toFirestore());

      debugPrint('✅ [APPLICATION] Application saved: ${user.email} → ${project.title}');
    } catch (e) {
      debugPrint('❌ [APPLICATION] Error applying to project: $e');
      rethrow;
    }
  }

  /// Get all applications for a specific project
  Stream<List<ProjectApplication>> getApplicationsForProject(String projectId) {
    return _applicationsCollection
        .where('projectId', isEqualTo: projectId)
        .orderBy('appliedAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ProjectApplication.fromFirestore(doc))
            .toList())
        .handleError((error) {
          debugPrint('❌ [APPLICATION] Error in applications stream: $error');
          return <ProjectApplication>[];
        });
  }

  /// Get all applications for projects owned by a specific NGO
  Stream<List<ProjectApplication>> getApplicationsForNGO(String ngoId) {
    return _applicationsCollection
        .where('ngoId', isEqualTo: ngoId)
        .orderBy('appliedAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ProjectApplication.fromFirestore(doc))
            .toList())
        .handleError((error) {
          debugPrint('❌ [APPLICATION] Error in NGO applications stream: $error');
          return <ProjectApplication>[];
        });
  }

  /// Get all applications by a specific user
  Stream<List<ProjectApplication>> getUserApplications(String userId) {
    return _applicationsCollection
        .where('userId', isEqualTo: userId)
        .orderBy('appliedAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ProjectApplication.fromFirestore(doc))
            .toList())
        .handleError((error) {
          debugPrint('❌ [APPLICATION] Error in user applications stream: $error');
          return <ProjectApplication>[];
        });
  }

  /// Get current user's applications
  Stream<List<ProjectApplication>> getCurrentUserApplications() {
    final user = _auth.currentUser;
    if (user == null) {
      return Stream.value([]);
    }
    return getUserApplications(user.uid);
  }

  /// Check if current user has applied to a project
  Future<bool> hasUserApplied(String projectId) async {
    final user = _auth.currentUser;
    if (user == null) return false;

    try {
      final snapshot = await _applicationsCollection
          .where('userId', isEqualTo: user.uid)
          .where('projectId', isEqualTo: projectId)
          .limit(1)
          .get();

      return snapshot.docs.isNotEmpty;
    } catch (e) {
      debugPrint('❌ [APPLICATION] Error checking application: $e');
      return false;
    }
  }

  /// Update application status
  Future<void> updateApplicationStatus(
    String applicationId,
    ApplicationStatus status,
  ) async {
    try {
      await _applicationsCollection.doc(applicationId).update({
        'status': status.name,
        'lastUpdated': FieldValue.serverTimestamp(),
      });
      debugPrint('✅ [APPLICATION] Application status updated: $applicationId → ${status.name}');
    } catch (e) {
      debugPrint('❌ [APPLICATION] Error updating application status: $e');
      rethrow;
    }
  }

  /// Delete an application
  Future<void> deleteApplication(String applicationId) async {
    try {
      await _applicationsCollection.doc(applicationId).delete();
      debugPrint('✅ [APPLICATION] Application deleted: $applicationId');
    } catch (e) {
      debugPrint('❌ [APPLICATION] Error deleting application: $e');
      rethrow;
    }
  }
}

