// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdAgRimZ8Nk8V14gsA6_o_WqKcfz7UQE',
    appId: '1:950924265668:web:4335da1db5cd1da5206191',
    messagingSenderId: '950924265668',
    projectId: 'tmelnikapp',
    authDomain: 'tmelnikapp.firebaseapp.com',
    storageBucket: 'tmelnikapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdAgRimZ8Nk8V14gsA6_o_WqKcfz7UQE',
    appId: '1:950924265668:android:your-android-app-id',
    messagingSenderId: '950924265668',
    projectId: 'tmelnikapp',
    storageBucket: 'tmelnikapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdAgRimZ8Nk8V14gsA6_o_WqKcfz7UQE',
    appId: '1:950924265668:ios:your-ios-app-id',
    messagingSenderId: '950924265668',
    projectId: 'tmelnikapp',
    storageBucket: 'tmelnikapp.firebasestorage.app',
    iosBundleId: 'com.example.tmelnikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdAgRimZ8Nk8V14gsA6_o_WqKcfz7UQE',
    appId: '1:950924265668:ios:your-macos-app-id',
    messagingSenderId: '950924265668',
    projectId: 'tmelnikapp',
    storageBucket: 'tmelnikapp.firebasestorage.app',
    iosBundleId: 'com.example.tmelnikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvdAgRimZ8Nk8V14gsA6_o_WqKcfz7UQE',
    appId: '1:950924265668:web:4335da1db5cd1da5206191',
    messagingSenderId: '950924265668',
    projectId: 'tmelnikapp',
    storageBucket: 'tmelnikapp.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBvdAgRimZ8Nk8V14gsA6_o_WqKcfz7UQE',
    appId: '1:950924265668:web:4335da1db5cd1da5206191',
    messagingSenderId: '950924265668',
    projectId: 'tmelnikapp',
    storageBucket: 'tmelnikapp.firebasestorage.app',
  );
}
